# Generated by Django 5.2 on 2025-09-12 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleep_time', models.TimeField()),
                ('wake_time', models.TimeField()),
                ('energy_level', models.CharField(max_length=10)),
                ('sunlight_time', models.IntegerField()),
                ('exercise_time', models.IntegerField(blank=True, null=True)),
                ('last_meal_time', models.TimeField(blank=True, null=True)),
                ('stress_level', models.CharField(blank=True, max_length=10, null=True)),
                ('ai_report', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
