# Generated by Django 5.2 on 2025-09-13 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsubmission',
            name='dietary_habits',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizsubmission',
            name='medication',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizsubmission',
            name='work_schedule',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
